import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "./style.css";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { locales } from "@/config";

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }));
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { lng } = await params;
  return (
    <html lang={lng}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container">
          <Header />
          <div className="main">
            <section>
              <Footer lng={lng} />
              <Sidebar lng={lng} />
            </section>
            <section className="col note-viewer">{children}</section>
          </div>
        </div>
      </body>
    </html>
  );
}
